### ISSUE TITLE
Uncertainty regarding arrays as parameters.

### ISSUE THREAD

**Issue by raxiam** [Atherys-Horizons/AtherysQuests#39]
**Problem:**
In the signature of functions, parameters that are arrays are written in plural form as opposed to singular, making them sometimes go unnoticed. 

**Proposed Solution:**
Denote arrays with [] for the parameter name.

Ex: Boolean addQuestRewards(Quest quest, Reward [rewards])

**Comment by HaedHutner** [comment]
Rather a more correct example would be
```
Boolean addQuestRewards(Quest quest, Reward[] rewards)
```

@LJNIC Since you're the docs guy, I'm assigning this to you

**Comment by raxiam** [comment]
Yeah, go with heads example.

**Comment by fingoltin** [comment]
This is fixed in the latest commits to the [AtherysDoclet](https://github.com/Atherys-Horizons/AtherysDoclet). I'm not sure where future issues with documentation should go. The documentation is mostly written in the code itself, but generated by the previously mentioned Doclet, and then pushed to [AtherysDocs](https://github.com/Atherys-Horizons/AtherysDocs).
